In [1]:
import numpy as np
import pandas as pd
import os
import json
from dateutil import parser
from zipfile import ZipFile


json.loads("[1,2,3]")

[1, 2, 3]

In [2]:
CA_rule_order = [7, 178, 2, 130, 108, 24, 152, 34, 35, 162, 10, 46, 138, 15, 11, 56, 184, 42, 57, 25, 9, 94, 62, 58, 26, 154,
            170, 72, 13, 77, 78, 140, 4, 44, 172, 5, 132, 164, 38, 1, 33, 156, 28, 74, 142, 43, 6, 29, 14, 37, 3, 134,
            27, 73, 19, 50, 51, 76, 204, 12, 36, 18, 22, 30, 45, 122, 126, 146, 60, 90, 105, 150, 54, 41, 106, 110, ]

performence_perf_param_i = {}

performence_perf_param_i[1] = [0,0,0,0,0,0,0,7,0,9,12,0,14,99,0,97,27,37,0,0,0,0,0,0,0,0,100,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,73,95,92,0,0,0,0]
performence_perf_param_i[2] = [0,0,0,0,0,0,0,22,0,27,30,0,8,11,0,0,0,89,0,1,4,0,0,0,0,0,100,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,2,0,0,2,0,0,1,6,11,7,61,0,0,0,0,0,0,0,0,0,0,0,0,0,0,100,100,88,92,0,0,0,0]
performence_perf_param_i[3] = [0,0,14,23,0,1,1,78,0,89,72,1,75,100,2,64,7,98,0,0,6,0,5,0,9,97,100,0,0,0,0,0,0,0,0,0,0,0,32,0,0,0,0,23,0,0,8,0,0,0,0,12,23,99,0,0,0,0,0,0,0,26,0,0,0,0,0,27,65,89,100,100,31,3,0,0]
performence_perf_param_i[4] = [0,0,35,40,0,15,11,88,0,91,90,37,93,14,0,1,1,98,0,0,0,0,3,0,100,100,100,0,0,0,0,0,0,0,0,0,0,0,61,0,0,0,0,39,0,0,40,0,0,0,3,47,18,100,0,0,0,0,0,0,0,99,100,100,100,98,95,97,100,100,100,100,74,100,100,100]

In [3]:
data = {
#     "Benchmark": ["X-bit","X-bit","X-bit","X-bit"],
#     "R": [4,4,4,4],
#     "I": [1,2,3,4],
#     "Dp": [200,200,200,200],
#     "Ld": [40,40,40,40],
#     "Nb": [5,5,5,5]
       
       }

macro = pd.DataFrame(data, columns=["Benchmark", "R", "I", "Dp", "Ld", "Nb"])
macro = macro.astype(
    {'Benchmark': 'str',
     'R': 'int',
     'I': 'int',
     'Dp': 'int',
     'Ld': 'int',
     'Nb': 'int'}
)
macro

Empty DataFrame
Columns: [Benchmark, R, I, Dp, Ld, Nb]
Index: []

In [4]:
data = {
    
}

exp = pd.DataFrame(data, columns=["macroExperiment", "CARule", "StartTime"])
# for i in range(0,4):
#     for ca_rule in CA_rule_order:
#         exp = exp.append({"macroExperiement":i, "CARule": ca_rule}, ignore_index=True
# )
    
exp
exp = exp.astype(
    {'macroExperiment': 'int',
     'CARule': 'int',
     'StartTime': 'datetime64[ns]'}
)
exp

Empty DataFrame
Columns: [macroExperiment, CARule, StartTime]
Index: []

In [5]:
data = {}
run = pd.DataFrame(data, columns=["Experiment", "Avg", "RandomMapping"])
run

Empty DataFrame
Columns: [Experiment, Avg, RandomMapping]
Index: []

In [6]:
%%time

def paramsToDict(params):
    dictP = {}
    for pa in params:
        arrayP = pa.split("=")
        if len(arrayP) != 2:
            arrayP = ["started at", "".join(arrayP[0].split(":")[1:5]).replace("\n", "")]
#         print(arrayP)
        dictP[arrayP[0].strip()] = arrayP[1]
    return dictP

from zipfile import ZipFile
directory = "import"
for zipname in os.listdir(directory):
    with ZipFile(os.path.join(directory, zipname), "r") as zip:
        for filename in zip.namelist():
            with zip.open(filename) as file:
                lines = file.readlines()
                params = (lines[0].decode("utf-8")).split(",")
                dictP = paramsToDict(params)
#                 print(dictP)
                ex = {
                    "Nb": int(dictP.get("bits", 5)),
                    "R" : int(dictP.get("r", -1)),
                    "I" : int(dictP.get("itr", -1)),
                    "Ld": int(dictP.get("r width")) if dictP.get("r width") != None else int(dictP.get("r total width", -1) / int(dictP.get("r", -1)) ),
                    "Dp": int(dictP.get("distractor period", -1)),
                    "CA": int(dictP.get("CA rule", -1)),
                    "Nruns": int(dictP.get("number of runs", -1)),
                    "StartTime": parser.parse(dictP.get("started at", -1)),
                }
                exIndex = exp.index.size
                macroExp = macro[(macro["Nb"]==ex["Nb"])
                         & (macro["R"]==ex["R"])
                         & (macro["I"]==ex["I"])
                         & (macro["Ld"]==ex["Ld"])
                         & (macro["Dp"]==ex["Dp"])
                            ]
                macroIndex = None
                if(macroExp.empty):
                    macroIndex = macro.index.size
                    macro = macro.append({"Benchmark":"X-Bit", "Nb": ex["Nb"],"R": ex["R"],"I": ex["I"],"Ld": ex["Ld"],"Dp": ex["Dp"]}, ignore_index=True)
                else:
                    macroIndex = macroExp.index.max()
                exp =exp.append({"macroExperiment": macroIndex, "CARule":ex["CA"], "StartTime": ex["StartTime"]}, ignore_index=True)

                runs = lines[2:ex["Nruns"]+2]
                for inputRun in runs:
                    inputRun = inputRun.decode("utf-8")
                    Score = float(inputRun.split("\t")[0])
                    map = json.loads((inputRun.split("\t")[1]).replace("\n", ""))
                    run = run.append({"Experiment": exIndex, "Avg":Score, "RandomMapping":map}, ignore_index=True)

Wall time: 44min 51s

In [3]:
macro

    Benchmark  R  I    Dp   Ld  Nb
0       X-Bit  4  2   100   40   5
1       X-Bit  4  2   300   40   5
2       X-Bit  4  2  4000   40   5
3       X-Bit  4  2    50   40   5
4       X-Bit  1  1   195   35   5
..        ... .. ..   ...  ...  ..
375     X-Bit  3  2   200  166   5
376     X-Bit  3  2   200  167   5
377     X-Bit  3  2   200  168   5
378     X-Bit  3  2   200  169   5
379     X-Bit  5  2   200   40   5

[380 rows x 6 columns]

In [4]:
exp

      macroExperiment  CARule                   StartTime
0                   0       0  2021-03-28 15:32:43.760279
1                   0       1  2021-03-28 16:15:39.122867
2                   0       2  2021-03-28 16:58:00.030187
3                   0       3  2021-03-28 17:40:20.498386
4                   0       4  2021-03-28 18:23:19.159263
...               ...     ...                         ...
3808              379     251  2021-01-14 08:55:28.789110
3809              379     252  2021-01-14 09:43:32.486915
3810              379     253  2021-01-14 10:31:34.239061
3811              379     254  2021-01-14 11:19:37.569620
3812              379     255  2021-01-14 12:07:41.782386

[3813 rows x 3 columns]

In [5]:
run

,Experiment,Avg,RandomMapping
0,0,0.954545,"[30, 8, 1, 35, 61, 49, 40, 45, 93, 101, 94, 11..."
1,0,0.954545,"[24, 13, 38, 5, 61, 49, 40, 69, 94, 100, 111, ..."
2,0,0.954545,"[6, 20, 36, 11, 46, 75, 43, 52, 91, 117, 103, ..."
3,0,0.954545,"[13, 32, 6, 39, 64, 46, 45, 71, 109, 115, 80, ..."
4,0,0.954545,"[8, 21, 29, 10, 52, 45, 51, 54, 115, 111, 85, ..."
...,...,...,...
381295,3812,0.976190,"[11, 30, 6, 3, 44, 70, 49, 76, 101, 91, 106, 9..."
381296,3812,0.976190,"[4, 37, 0, 3, 47, 43, 45, 64, 118, 99, 106, 94..."
381297,3812,0.976190,"[27, 22, 26, 24, 73, 79, 54, 49, 83, 118, 109,..."
381298,3812,0.976190,"[34, 24, 35, 1, 79, 66, 54, 69, 92, 84, 105, 1..."
381299,3812,0.976190,"[10, 6, 24, 4, 75, 62, 74, 48, 110, 86, 88, 11..."

In [ ]:
%%time
macro.to_csv("macro.csv")
exp.to_csv("exp.csv")
run.to_csv("run.csv")

In [2]:
%%time
macro = pd.read_csv('macro.csv', index_col=0)  
exp = pd.read_csv('exp.csv', index_col=0)  
run = pd.read_csv('run.csv', index_col=0)

Wall time: 513 ms

In [6]:
count = 0
def metrics(row):
    mn = (row.Dp.iloc[0]+row.Nb.iloc[0])/(row.Dp.iloc[0]+(2*row.Nb.iloc[0]))
    count = row.Avg.count()
    mean = row.Avg.mean()
    perf = row.Avg[row.Avg==1.0].count()
    ob = pd.Series(data = {"W.Avg." : (mean - mn)/(1-mn), "mean": mean, "perf": perf, "count":count})
    return ob


mega = pd.merge(macro, pd.merge(exp, run, right_on="Experiment", left_index=True), right_on="macroExperiment", left_index=True)

megaG = mega.groupby(["macroExperiment", "I", "Nb", "Dp", "CARule", "Ld"])

megaG.apply(metrics)

                                          W.Avg.      mean  perf  count
macroExperiment I Nb Dp  CARule Ld
0               2 5  100 0      40 -2.198242e-14  0.954545   0.0  100.0
                         1      40  5.686250e-01  0.980392   0.0  100.0
                         2      40  5.000000e-01  0.977273   0.0  100.0
                         3      40  9.624375e-01  0.998293   7.0  100.0
                         4      40  5.200000e-01  0.978182   0.0  100.0
...                                          ...       ...   ...    ...
379             2 5  200 251    40  4.196643e-14  0.976190   0.0  100.0
                         252    40  4.196643e-14  0.976190   0.0  100.0
                         253    40  4.196643e-14  0.976190   0.0  100.0
                         254    40  4.196643e-14  0.976190   0.0  100.0
                         255    40  4.196643e-14  0.976190   0.0  100.0

[3469 rows x 4 columns]

In [7]:
megaGC = megaG.count()

In [9]:
megaGC[megaGC != 100].dropna().head(50)

                                     Benchmark      R  StartTime  Experiment  \
macroExperiment I Nb Dp  CARule Ld
130             2 5  200 170    35       200.0  200.0      200.0       200.0
141             2 5  200 170    36       200.0  200.0      200.0       200.0
152             2 5  200 170    37       200.0  200.0      200.0       200.0
163             2 5  200 170    38       200.0  200.0      200.0       200.0
174             2 5  200 170    39       200.0  200.0      200.0       200.0
180             2 5  195 90     40       200.0  200.0      200.0       200.0
181             2 5  196 90     40       200.0  200.0      200.0       200.0
182             2 5  197 90     40       200.0  200.0      200.0       200.0
183             2 5  198 90     40       200.0  200.0      200.0       200.0
184             2 5  199 90     40       200.0  200.0      200.0       200.0
185             2 5  200 90     40       200.0  200.0      200.0       200.0
                         170    40       200.0  200.0      200.0       200.0
186             2 5  201 90     40       200.0  200.0      200.0       200.0
187             2 5  202 90     40       200.0  200.0      200.0       200.0
188             2 5  203 90     40       200.0  200.0      200.0       200.0
189             2 5  204 90     40       200.0  200.0      200.0       200.0
190             2 5  205 90     40       200.0  200.0      200.0       200.0
196             2 5  200 170    41       200.0  200.0      200.0       200.0
207             2 5  200 170    42       200.0  200.0      200.0       200.0
218             2 5  200 170    43       200.0  200.0      200.0       200.0
229             2 5  200 170    44       200.0  200.0      200.0       200.0
240             2 5  200 170    45       200.0  200.0      200.0       200.0
265             2 5  200 90     160      200.0  200.0      200.0       200.0
297             2 5  200 10     40       200.0  200.0      200.0       200.0
                         54     40       200.0  200.0      200.0       200.0
                         60     40       200.0  200.0      200.0       200.0
                         90     40       200.0  200.0      200.0       200.0
                         240    40       200.0  200.0      200.0       200.0
334             2 3  200 0      160      200.0  200.0      200.0       200.0
                         1      160      200.0  200.0      200.0       200.0
                         2      160      200.0  200.0      200.0       200.0
                         3      160      200.0  200.0      200.0       200.0
                         4      160      200.0  200.0      200.0       200.0
                         5      160      200.0  200.0      200.0       200.0
                         6      160      200.0  200.0      200.0       200.0
                         7      160      200.0  200.0      200.0       200.0
                         8      160      200.0  200.0      200.0       200.0
                         9      160      200.0  200.0      200.0       200.0
                         10     160      200.0  200.0      200.0       200.0
                         11     160      200.0  200.0      200.0       200.0
                         12     160      200.0  200.0      200.0       200.0
                         13     160      200.0  200.0      200.0       200.0
                         14     160      200.0  200.0      200.0       200.0
                         15     160      200.0  200.0      200.0       200.0
                         16     160      200.0  200.0      200.0       200.0
                         17     160      200.0  200.0      200.0       200.0
                         18     160      200.0  200.0      200.0       200.0
                         19     160      200.0  200.0      200.0       200.0
                         20     160      200.0  200.0      200.0       200.0
                         21     160      200.0  200.0      200.0       200.0

                                       Avg  RandomMapping
macroExperiment I Nb Dp  CARule Ld
130             2 5  200 170    35   200.0          200.0
141             2 5  200 170    36   200.0          200.0
152             2 5  200 170    37   200.0          200.0
163             2 5  200 170    38   200.0          200.0
174             2 5  200 170    39   200.0          200.0
180             2 5  195 90     40   200.0          200.0
181             2 5  196 90     40   200.0          200.0
182             2 5  197 90     40   200.0          200.0
183             2 5  198 90     40   200.0          200.0
184             2 5  199 90     40   200.0          200.0
185             2 5  200 90     40   200.0          200.0
                         170    40   200.0          200.0
186             2 5  201 90     40   200.0          200.0
187             2 5  202 90     40   200.0          200.0
188             2 5  203 90     40   200.0          200.0
189             2 5  204 90     40   200.0          200.0
190             2 5  205 90     40   200.0          200.0
196             2 5  200 170    41   200.0          200.0
207             2 5  200 170    42   200.0          200.0
218             2 5  200 170    43   200.0          200.0
229             2 5  200 170    44   200.0          200.0
240             2 5  200 170    45   200.0          200.0
265             2 5  200 90     160  200.0          200.0
297             2 5  200 10     40   200.0          200.0
                         54     40   200.0          200.0
                         60     40   200.0          200.0
                         90     40   200.0          200.0
                         240    40   200.0          200.0
334             2 3  200 0      160  200.0          200.0
                         1      160  200.0          200.0
                         2      160  200.0          200.0
                         3      160  200.0          200.0
                         4      160  200.0          200.0
                         5      160  200.0          200.0
                         6      160  200.0          200.0
                         7      160  200.0          200.0
                         8      160  200.0          200.0
                         9      160  200.0          200.0
                         10     160  200.0          200.0
                         11     160  200.0          200.0
                         12     160  200.0          200.0
                         13     160  200.0          200.0
                         14     160  200.0          200.0
                         15     160  200.0          200.0
                         16     160  200.0          200.0
                         17     160  200.0          200.0
                         18     160  200.0          200.0
                         19     160  200.0          200.0
                         20     160  200.0          200.0
                         21     160  200.0          200.0